spring.application.name=Baraka

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.change-log=classpath:db/changelog/changelog-master.xml
spring.liquibase.enabled=true

spring.jackson.serialization.indent_output=true

storage.local.path=uploads/documents